wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691994173.500179
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 7
      - 17
      - 23
      - 37
      4: 3.10.2
      5: 0.15.8
      8:
      - 4
      - 5
      10:
      - 3
    m:
    - 1: custom_step
      6:
      - 3
    - 1: episode_reward_mean
      5: 1
      6:
      - 1
